services:
  mybot:
    image: bot:0.0.1
    container_name: bot_translater
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - .postgresql:/var/lib/postgresql/data
